import turtle

turtle.speed('fast')
turtle.width(7)

turtle.up()
turtle.setposition(-50, 0)
turtle.down()

turtle.color('blue')
turtle.left(105)
turtle.forward(100)
turtle.left(75)
turtle.forward(30)
turtle.up()
turtle.left(180)
turtle.forward(30)
turtle.right(75)
turtle.forward(28)
turtle.left(75)
turtle.down()
turtle.forward(180)
turtle.right(105)
turtle.forward(90)
turtle.right(75)
turtle.forward(133)
turtle.left(105)
turtle.forward(17)
turtle.left(75)
turtle.forward(125)

turtle.up()
turtle.setposition(-22, -67)
turtle.down()
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()

turtle.up()
turtle.setposition(68, -67)
turtle.down()
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()

turtle.up()
turtle.setposition(22, -11)
turtle.left(90)
turtle.down()
turtle.color('light blue')
turtle.width(5)
turtle.forward(75.5)

turtle.up()
turtle.setposition(55, -11)
turtle.right(11)
turtle.down()
turtle.color('light blue')
turtle.width(5)
turtle.forward(76)

turtle.up()
turtle.setposition(-11, -11)
turtle.left(22)
turtle.down()
turtle.color('light blue')
turtle.width(5)
turtle.forward(76)

turtle.up()
turtle.setposition(-46, 10)
turtle.right(101)
turtle.down()
turtle.color('light blue')
turtle.width(5)
turtle.forward(135)

turtle.up()
turtle.setposition(-54, 40)
turtle.down()
turtle.color('light blue')
turtle.width(5)
turtle.forward(151)

turtle.done()
